# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "50460f67910f9fc279dd73d3bf38ceb3"
name = "USP Bar test"
application_url = "https://banner-slider-web.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://banner-slider-backend.onrender.com/api/shopify/webhook"


[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes"

[auth]
redirect_urls = [
  "https://banner-slider-web.onrender.com/auth/callback",
  "https://banner-slider-web.onrender.com/auth/shopify/callback",
  "https://banner-slider-web.onrender.com/api/auth/callback"
]
